### ISSUE TITLE
Split CI to check newest dependencies

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#395] opened 2022-05-09 16:48 UTC
## Description

Ideally, we want to split our CI process into two. One tests our connector against a fixed version and the other tests against the latest releases.

**Comment by jeremyp-bq** [comment] 2022-07-14 17:37
Covered by #421?

**Comment by jonathanl-bq** [comment] 2022-07-15 19:06
Closed as duplicate of #421

**Closed by jonathanl-bq** 2022-07-15 19:06 UTC
Labels: enhancement, testing, ci
